version: '2.2'

services:
  web:
    build:
      context: .
      dockerfile: multistage-docker-reactjs
    ports:
      - "80"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    


