apiVersion: v1
kind: Service
metadata:
  name: react-deployment
spec:
  type: NodePort     
  selector:
    app: raam
  ports:
    - name: http
      protocol: TCP 
      port: 80
      targetPort: 80
